/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gridcreator;

import java.awt.Font;

/**
 *
 * @author Thilina Jayamini - thilinajayamini@gmail.com
 */
public class UI2 extends UIM {

    /**
     * Creates new form UI2
     */
    public UI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(128, 128, 128));
        jPanel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 150));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 150));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 140));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 140));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 140));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setMaximumSize(new java.awt.Dimension(300, 140));
        jTextArea1.setMinimumSize(new java.awt.Dimension(300, 140));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    @Override
    public void setContent(String msg){
        this.jTextArea1.setText(msg);
   }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
   public void setMyFont(Font f){
        this.jTextArea1.setFont(f);
   }
}
